blueprint:
  name: Samsung AC Error Notification
  description: >
    This blueprint monitors a selected sensor for specific error codes from Samsung AC units 
    and sends notifications to a chosen device with a detailed error message.
  domain: automation
  input:
    sensor_entity:
      name: Error Code Sensor
      description: The sensor that monitors the AC error codes.
      selector:
        entity:
          domain: sensor
    
    notify_device:
      name: Device to notify
      description: Device needs to run the official Home Assistant app to receive notifications.
      selector:
        device:
          integration: mobile_app
    
    is_ios:
      name: Is it an iOS device?
      description: Toggle if your selected device runs iOS, default is Android.
      selector:
        boolean:
      default: false

    notification_title:
      name: Notification title (Optional)
      description: 'Default: "Samsung AC Error Detected"'
      default: "Samsung AC Error Detected"
      
    notification_message:
      name: Notification message (Optional)
      description: 'Default: {{ error_code }} : {{ error_message }}'
      default: "{{ error_code }} : {{ error_message }}"

trigger:
  platform: state
  entity_id: !input sensor_entity

variables:
  error_code: "{{ states[trigger.entity_id].state }}"
  error_message: >
    {% if error_code == 0 %}
      All AC units are operating normally. No errors detected.
    {% elif error_code == "unavailable" %}
      The device is currently offline. Please check the connection.
    {% elif error_code == 101 %}
      Indoor unit communication error. Indoor unit cannot receive any data from the outdoor unit.
    {% elif error_code == 102 %}
      Communication error between indoor unit and outdoor unit. Displayed in indoor unit.
    {% elif error_code == 108 %}
      Error due to repeated address setting (When 2 or more devices have the same address within the system).
    {% elif error_code == 110 %}
      Communication error between Hydro unit HT (Main PBA) and Control kit PBA (Detection from the Control kit).
    {% elif error_code == 121 %}
      Error on indoor temperature sensor of indoor unit (Short or Open).
    {% elif error_code == 122 %}
      Error on EVA IN sensor of indoor unit (Short or Open).
    {% elif error_code == 123 %}
      Error on EVA OUT sensor of indoor unit (Short or Open).
    {% elif error_code == 128 %}
      EVA IN temperature sensor of indoor unit is detached from EVA IN pipe.
    {% elif error_code == 129 %}
      EVA OUT temperature sensor of indoor unit is detached from EVA OUT pipe.
    {% elif error_code == 130 %}
      Heat exchanger in/out sensors of indoor unit are detached.
    {% elif error_code == 135 %}
      RPM feedback error of indoor unit's cleaning fan.
    {% elif error_code == 151 %}
      Error due to opened EEV of indoor unit (2nd detection).
    {% elif error_code == 152 %}
      Error due to closed EEV of indoor unit (2nd detection).
    {% elif error_code == 153 %}
      Error on floating switch of indoor unit (2nd detection).
    {% elif error_code == 154 %}
      RPM feedback error of indoor unit.
    {% elif error_code == 161 %}
      Mixed operation mode error of indoor unit; When the outdoor unit is getting ready to operate in cooling (or heating) and some of the indoor unit is trying to operate in heating (or cooling) mode.
    {% elif error_code == 162 %}
      EEPROM error of MICOM (Physical problem of parts/circuit).
    {% elif error_code == 163 %}
      Indoor unit's remote controller option input is incorrect or missing. Outdoor unit EEPROM data error.
    {% elif error_code == 180 %}
      Simultaneous opening of cooling/heating MCU SOL V/V (1st detection).
    {% elif error_code == 181 %}
      Simultaneous opening of cooling/heating MCU SOL V/V (2nd detection).
    {% elif error_code == 185 %}
      Cross wiring error between communication and power cable of indoor unit.
    {% elif error_code == 186 %}
      Connection error or problem on SPi.
    {% elif error_code == 190 %}
      No temperature changes in EVA IN during pipe inspection or changes in temperature in the indoor unit with wrong address.
    {% elif error_code == 191 %}
      No temperature changes in EVA OUT during pipe inspection or changes in temperature in the indoor unit with wrong address.
    {% elif error_code == 198 %}
      Error due to disconnected thermal fuse of indoor unit.
    {% elif error_code == 201 %}
      Communication error between indoor and outdoor units (installation number setting error, repeated indoor unit address, indoor unit communication cable error).
    {% elif error_code == 202 %}
      Communication error between indoor and outdoor units (Communication error on all indoor units, outdoor unit communication cable error).
    {% elif error_code == 203 %}
      Communication error between main and sub outdoor units.
    {% elif error_code == 205 %}
      Communication error on all PBA within the outdoor unit C-Box, communication cable error.
    {% elif error_code == 206 %}
      HUB PBA communication error / FAN PBA communication error / INV1 PBA communication error / INV2 PBA communication error.
    {% elif error_code == 211 %}
      When single indoor unit uses 2 MCU ports that are not in series.
    {% elif error_code == 212 %}
      If the rotary switch (on the MCU) for address setting of the indoor unit has 3 or more of the same address.
    {% elif error_code == 213 %}
      When total number of indoor units assigned to MCU is the same as the actual number of installed indoor units but there is an indoor unit that is not installed even though it is assigned on MCU.
    {% elif error_code == 214 %}
      When the number of MCU is not set correctly on the outdoor unit or when two or more MCUs were installed and some of them have the same address.
    {% elif error_code == 215 %}
      When two different MCUs have the same address value on the rotary switch.
    {% elif error_code == 216 %}
      When the indoor unit is not installed to an MCU port but the switch on the port is set to On.
    {% elif error_code == 217 %}
      When the indoor unit is connected to an MCU port but the indoor unit is assigned to an MCU and the switch on the port is set to Off.
    {% elif error_code == 218 %}
      When there’s at least one or more actual number of indoor unit connections compared to the number of indoor units assigned to MCU.
    {% elif error_code == 219 %}
      Error on temperature sensor located on MCU intercooler inlet (Short or Open).
    {% elif error_code == 220 %}
      Error on temperature sensor located on MCU intercooler outlet (Short or Open).
    {% elif error_code == 221 %}
      Error on outdoor temperature sensor of the outdoor unit (Short or Open).
    {% elif error_code == 231 %}
      Error on COND OUT temperature sensor of the main outdoor unit (Short or Open).
    {% elif error_code == 241 %}
      COND OUT sensor is detached.
    {% elif error_code == 251 %}
      Error on discharge temperature sensor of compressor 1 (Short or Open).
    {% elif error_code == 257 %}
      Error on discharge temperature sensor of compressor 2 (Short or Open).
    {% elif error_code == 262 %}
      Discharge temperature sensor of compressor 1 is detached from the sensor holder on the pipe.
    {% elif error_code == 263 %}
      Discharge temperature sensor of compressor 2 is detached from the sensor holder on the pipe.
    {% elif error_code == 266 %}
      Top sensor of compressor 1 is detached.
    {% elif error_code == 267 %}
      Top sensor of compressor 2 is detached.
    {% elif error_code == 269 %}
      Suction temperature sensor is detached from the sensor holder on the pipe.
    {% elif error_code == 276 %}
      Error on top sensor of compressor 1 (Short or Open).
    {% elif error_code == 277 %}
      Error on top sensor of compressor 2 (Short or Open).
    {% elif error_code == 291 %}
      Refrigerant leakage or error on high pressure sensor (Short or Open).
    {% elif error_code == 296 %}
      Refrigerant leakage or error on low pressure sensor (Short or Open).
    {% elif error_code == 308 %}
      Error on suction temperature sensor (Short or Open).
    {% elif error_code == 311 %}
      Error on temperature sensor of double-layer pipe/liquid pipe (sub heat exchanger) (Short or Open).
    {% elif error_code == 321 %}
      Error on EVI (ESC) IN temperature sensor (Short or Open).
    {% elif error_code == 322 %}
      Error on EVI (ESC) OUT temperature sensor (Short or Open).
    {% elif error_code == 323 %}
      Error on suction sensor 2 (Short or Open).
    {% elif error_code == 346 %}
      Error due to operation failure of Fan2.
    {% elif error_code == 347 %}
      Motor wire of Fan2 is not connected.
    {% elif error_code == 348 %}
      Lock error on Fan2 of the outdoor unit.
    {% elif error_code == 353 %}
      Error due to overload motor of the outdoor unit's Fan2.
    {% elif error_code == 355 %}
      Error due to overheated IPM of Fan2.
    {% elif error_code == 361 %}
      Error due to operation failure of inverter compressor 2.
    {% elif error_code == 364 %}
      Error due to over-current of inverter compressor 2.
    {% elif error_code == 365 %}
      V-limit error of inverter compressor 2.
    {% elif error_code == 366 %}
      Error due to over-voltage / low voltage of inverter PBA2.
    {% elif error_code == 367 %}
      Error due to unconnected wire of compressor 2.
    {% elif error_code == 368 %}
      Output current sensor error of inverter PBA2.
    {% elif error_code == 369 %}
      DC voltage sensor error of inverter PBA2.
    {% elif error_code == 374 %}
      Heat sink temperature sensor error of inverter PBA2.
    {% elif error_code == 376 %}
      Error due to over-current of Fan2.
    {% elif error_code == 378 %}
      Error due to input current of inverter 2.
    {% elif error_code == 386 %}
      Over-voltage/low-voltage error of Fan2.
    {% elif error_code == 387 %}
      Hall IC connection error of Fan2.
    {% elif error_code == 389 %}
      V-limit error on Fan2 of compressor.
    {% elif error_code == 393 %}
      Output current sensor error of Fan2.
    {% elif error_code == 396 %}
      DC voltage sensor error of Fan2.
    {% elif error_code == 399 %}
      Heat sink temperature sensor error of Fan2.
    {% elif error_code == 400 %}
      Error due to overheat caused by contact failure on IPM of Inverter PBA2.
    {% elif error_code == 407 %}
      Compressor operation stop due to high pressure protection control.
    {% elif error_code == 410 %}
      Compressor operation stop due to low pressure protection control or refrigerant leakage.
    {% elif error_code == 413 %}
      Compressor operation stop due to discharge temperature protection control.
    {% elif error_code == 425 %}
      Phase reversal or phase failure (3φ outdoor unit wiring, R-S-T-N ), connection error on 3 phase input.
    {% elif error_code == 428 %}
      Compressor operation stop due to abnormal compression ratio.
    {% elif error_code == 438 %}
      EVI (ESC) EEV leakage or internal leakage of intercooler or incorrect connector insertion of EVI (ESC) EEV.
    {% elif error_code == 439 %}
      Error due to refrigerant leakage.
    {% elif error_code == 440 %}
      Heating mode restriction due to high air temperature.
    {% elif error_code == 441 %}
      Cooling mode restriction due to low air temperature.
    {% elif error_code == 442 %}
      Refrigerant charging restriction in heating mode when air temperature is over 15 °C.
    {% elif error_code == 443 %}
      Operation prohibited due to the pressure drop.
    {% elif error_code == 445 %}
      CCH is detached.
    {% elif error_code == 446 %}
      Error due to operation failure of Fan1.
    {% elif error_code == 447 %}
      Motor wire of Fan1 is not connected.
    {% elif error_code == 448 %}
      Lock error on Fan1.
    {% elif error_code == 452 %}
      Error due to ZPC detection circuit problem or power failure.
    {% elif error_code == 453 %}
      Error due to overheated motor of outdoor unit's Fan1.
    {% elif error_code == 455 %}
      Error due to overheated IPM of Fan1.
    {% elif error_code == 461 %}
      Error due to operation failure of inverter compressor 1.
    {% elif error_code == 462 %}
      Compressor stop due to full current control or error due to low current on CT2.
    {% elif error_code == 464 %}
      Error due to over-current of inverter compressor 1.
    {% elif error_code == 465 %}
      V-limit error of inverter compressor 1.
    {% elif error_code == 466 %}
      Error due to over voltage / low voltage of inverter PBA1.
    {% elif error_code == 467 %}
      Error due to unconnected wire of compressor 1.
    {% elif error_code == 468 %}
      Output current sensor error of inverter PBA1.
    {% elif error_code == 469 %}
      DC voltage sensor error of inverter PBA1.
    {% elif error_code == 474 %}
      Heat sink temperature sensor error of inverter PBA1.
    {% elif error_code == 478 %}
      Error due to overcurrent of Fan1.
    {% elif error_code == 482 %}
      Error due to input current of inverter 1.
    {% elif error_code == 486 %}
      Error due to over voltage / low voltage of Fan1.
    {% elif error_code == 487 %}
      Hall IC error of Fan1.
    {% elif error_code == 489 %}
      V-limit error on Fan1 of compressor.
    {% elif error_code == 493 %}
      Output current sensor error of Fan1.
    {% elif error_code == 496 %}
      DC voltage sensor error of Fan1.
    {% elif error_code == 499 %}
      Heat sink temperature sensor error of Fan1.
    {% elif error_code == 500 %}
      Error due to overheat caused by contact failure on IPM of Inverter PBA1.
    {% elif error_code == 503 %}
      Error due to alert the user to check if the service valve is closed.
    {% elif error_code == 504 %}
      Error due to self-diagnosis of compressor operation.
    {% elif error_code == 505 %}
      Error due to self-diagnosis of high pressure sensor.
    {% elif error_code == 506 %}
      Error due to self-diagnosis of low pressure sensor.
    {% elif error_code == 560 %}
      Outdoor unit's option switch setting error (when inappropriate option switch is on).
    {% elif error_code == 563 %}
      Error due to module installation of indoor unit with old version (Micom version needs to be updated).
    {% elif error_code == 573 %}
      Error due to using single type outdoor unit in a module installation.
    {% elif error_code == 601 %}
      Communication error between remote controller and the DVM Hydro unit / Hydro unit HT.
    {% elif error_code == 602 %}
      Communication error between master and slave remote controller.
    {% elif error_code == 604 %}
      Tracking error between remote controller and the DVM Hydro unit / Hydro unit HT.
    {% elif error_code == 618 %}
      Error due to exceeding maximum numbers of Hydro unit installation (16 units).
    {% elif error_code == 627 %}
      Error due to exceeding maximum numbers of wired remote controller installation (2 units).
    {% elif error_code == 633 %}
      Error caused by installing mixed models.
    {% elif error_code == 635 %}
      Remote controller's temperature sensor is disconnected or has a problem.
    {% elif error_code == 654 %}
      Data error on remote controller (Memory read/write error).
    {% elif error_code == 702 %}
      Error due to closed EEV of indoor unit (1st detection).
    {% elif error_code == 703 %}
      Error due to opened EEV of indoor unit (1st detection).
    {% elif error_code == 901 %}
      Error on the sensor of water inlet pipe (Short or Open).
    {% elif error_code == 902 %}
      Error on the sensor of water outlet pipe (Short or Open).
    {% elif error_code == 904 %}
      Error on water tank (Short or open).
    {% elif error_code == 907 %}
      Error due to pipe rupture protection.
    {% elif error_code == 908 %}
      Error due to freeze prevention (Re-operation is possible).
    {% elif error_code == 909 %}
      Error due to freeze prevention (Re-operation is impossible).
    {% elif error_code == 910 %}
      Water temperature sensor on water outlet pipe is detached.
    {% elif error_code == 911 %}
      Flow switch off error, when the switch is turned off within 10 seconds after a pump starts its operation (Re-operation is possible).
    {% elif error_code == 913 %}
      Six times detection for Flow Switch Error (Re-operation is not possible).
    {% elif error_code == 914 %}
      Error due to incorrect thermostat connection.
    {% elif error_code == 915 %}
      Error on DC fan (Non-operating).
    {% elif error_code == "unknown" %}
    {% else %}
      Unknown error code: {{ error_code }}. Please refer to the AC unit's manual.
    {% endif %}
  is_ios: !input is_ios
  notification_title: !input notification_title
  notification_message: !input notification_message

action:
  - device_id: !input notify_device
    domain: mobile_app
    type: notify
    title: "{{ notification_title }}"
    message: "{{ notification_message }}"
    data: >
      {% set ios_data = {} %}
      {% set android_data = {} %}
      {{ ios_data if is_ios else android_data }}

mode: single
